dataset:
  _target_: dataset.ProteinDataset
  contact_type: cb
  sample: No
  truncation_mode: random
  cache_dataset: Yes
loss:
  _target_: loss.MaskedBCE
training:
  use_custom_rope: Yes
  batch_size: 16
  budget_token: 5000000
  truncation_seq_length: 200
  optimizer:
    _target_: torch.optim.Adam
    lr: 0.0001
peft:
  _target_: peft.LoraConfig
  r: 8
  lora_alpha: 8
  target_modules: ["q_proj", "v_proj"]
  lora_dropout: 0.05
  bias: "none"
model:
  _target_: esm.pretrained.esm2_t6_8M_UR50D
model_wrapper:
  _target_: model.ContactsWrapper